//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	in.ServiceToken.DeepCopyInto(&out.ServiceToken)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitzSecret) DeepCopyInto(out *InitzSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitzSecret.
func (in *InitzSecret) DeepCopy() *InitzSecret {
	if in == nil {
		return nil
	}
	out := new(InitzSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitzSecretList) DeepCopyInto(out *InitzSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InitzSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitzSecretList.
func (in *InitzSecretList) DeepCopy() *InitzSecretList {
	if in == nil {
		return nil
	}
	out := new(InitzSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InitzSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitzSecretSpec) DeepCopyInto(out *InitzSecretSpec) {
	*out = *in
	in.Authentication.DeepCopyInto(&out.Authentication)
	out.ManagedSecretReference = in.ManagedSecretReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitzSecretSpec.
func (in *InitzSecretSpec) DeepCopy() *InitzSecretSpec {
	if in == nil {
		return nil
	}
	out := new(InitzSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedSecretReference) DeepCopyInto(out *ManagedSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedSecretReference.
func (in *ManagedSecretReference) DeepCopy() *ManagedSecretReference {
	if in == nil {
		return nil
	}
	out := new(ManagedSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsScope) DeepCopyInto(out *SecretsScope) {
	*out = *in
	if in.SecretVars != nil {
		in, out := &in.SecretVars, &out.SecretVars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsScope.
func (in *SecretsScope) DeepCopy() *SecretsScope {
	if in == nil {
		return nil
	}
	out := new(SecretsScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceToken) DeepCopyInto(out *ServiceToken) {
	*out = *in
	out.ServiceTokenSecretReference = in.ServiceTokenSecretReference
	in.SecretsScope.DeepCopyInto(&out.SecretsScope)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceToken.
func (in *ServiceToken) DeepCopy() *ServiceToken {
	if in == nil {
		return nil
	}
	out := new(ServiceToken)
	in.DeepCopyInto(out)
	return out
}
