# permissions for end users to view initzsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: initzsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: initzsecret-viewer-role
rules:
- apiGroups:
  - alpha.initializ.com
  resources:
  - initzsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alpha.initializ.com
  resources:
  - initzsecrets/status
  verbs:
  - get
